### ISSUE TITLE
panic: can not marshal string into unknown_type_10

### ISSUE THREAD

**Issue by fym201** [gocassa/gocassa#136]
I use the gocassa/examples/table1/table1.go do test but got the follow error:

<pre><code>
E:\dev\go_path\src\server\test>go run test.go
panic: can not marshal string into unknown_type_10

goroutine 1 [running]:
main.main()
        E:/dev/go_path/src/server/test/test.go:40 +0x3ae

goroutine 17 [IO wait]:
net.runtime_pollWait(0x3b5398, 0x72, 0xc082002fa0)
        c:/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc082018d70, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082022020, 0xc082018c60, 0x76a960, 0x7, 0x7f7780, 0xc082018c00, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc082018c00, 0xc082080000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc08207c000, 0xc082080000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:172 +0xeb
bufio.(*Reader).fill(0xc08207e000)
        c:/go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Read(0xc08207e000, 0xc082076070, 0x8, 0x8, 0xecdf33a51, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:207 +0x267
io.ReadAtLeast(0x25a00a0, 0xc08207e000, 0xc082076070, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:298 +0xed
io.ReadFull(0x25a00a0, 0xc08207e000, 0xc082076070, 0x8, 0x8, 0x5f740a, 0x0, 0x0)
        c:/go/src/io/io.go:316 +0x69
github.com/gocql/gocql.readHeader(0x25a00a0, 0xc08207e000, 0xc082076070, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        E:/dev/go_path/src/github.com/gocql/gocql/frame.go:311 +0xa8
github.com/gocql/gocql.(*Conn).recv(0xc082088000, 0x0, 0x0)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:363 +0x11f
github.com/gocql/gocql.(*Conn).serve(0xc082088000)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:344 +0x34
created by github.com/gocql/gocql.Connect
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:192 +0x74d

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc082002d0c)
        c:/go/src/runtime/sema.go:43 +0x2d
sync.(*WaitGroup).Wait(0xc082002d00)
        c:/go/src/sync/waitgroup.go:126 +0xbb
github.com/gocql/gocql.(*SimplePool).fillPool(0xc08205a090)
        E:/dev/go_path/src/github.com/gocql/gocql/connectionpool.go:327 +0x39f
created by github.com/gocql/gocql.NewSimplePool
        E:/dev/go_path/src/github.com/gocql/gocql/connectionpool.go:207 +0x5c7

goroutine 7 [select]:
github.com/gocql/gocql.(*Conn).exec(0xc082030ea0, 0x25a0028, 0xc082022040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:468 +0x872
github.com/gocql/gocql.(*Conn).startup(0xc082030ea0, 0xc08202ddd8, 0x0, 0x0)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:243 +0x211
github.com/gocql/gocql.Connect(0xc082002d20, 0xf, 0x2, 0x769180, 0x5, 0x23c34600, 0x80, 0x0, 0x0, 0x3b4318, ...)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:194 +0x76b
github.com/gocql/gocql.(*SimplePool).connect(0xc08205a090, 0xc082002d20, 0xf, 0x0, 0x0)
        E:/dev/go_path/src/github.com/gocql/gocql/connectionpool.go:228 +0x189
github.com/gocql/gocql.(*SimplePool).fillPool.func2(0xc082002d00, 0xc08205a090, 0xc082002d20, 0xf, 0x1)
        E:/dev/go_path/src/github.com/gocql/gocql/connectionpool.go:319 +0x7d
created by github.com/gocql/gocql.(*SimplePool).fillPool
        E:/dev/go_path/src/github.com/gocql/gocql/connectionpool.go:321 +0x420

goroutine 8 [IO wait]:
net.runtime_pollWait(0x3b52d8, 0x72, 0xc082002f90)
        c:/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc0820194f0, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc082022020, 0xc0820193e0, 0x76a960, 0x7, 0x7f7780, 0xc082005880, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc082019380, 0xc08200f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082022038, 0xc08200f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:172 +0xeb
bufio.(*Reader).fill(0xc08200c780)
        c:/go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Read(0xc08200c780, 0xc082002f80, 0x8, 0x8, 0xecdf33a51, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:207 +0x267
io.ReadAtLeast(0x25a00a0, 0xc08200c780, 0xc082002f80, 0x8, 0x8, 0x8, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:298 +0xed
io.ReadFull(0x25a00a0, 0xc08200c780, 0xc082002f80, 0x8, 0x8, 0x5f740a, 0x0, 0x0)
        c:/go/src/io/io.go:316 +0x69
github.com/gocql/gocql.readHeader(0x25a00a0, 0xc08200c780, 0xc082002f80, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        E:/dev/go_path/src/github.com/gocql/gocql/frame.go:311 +0xa8
github.com/gocql/gocql.(*Conn).recv(0xc082030ea0, 0x0, 0x0)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:363 +0x11f
github.com/gocql/gocql.(*Conn).serve(0xc082030ea0)
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:344 +0x34
created by github.com/gocql/gocql.Connect
        E:/dev/go_path/src/github.com/gocql/gocql/conn.go:192 +0x74d
exit status 2
</code></pre>

**Comment by fym201** [comment]
This is a gocql's bug when use cylladb
