### ISSUE TITLE
cannot known server error when ReadOne send out err object

### ISSUE THREAD

**Issue by slayercat** [gocassa/gocassa#151]
when use gocassa like this:

```
   if err:= sessionsTable.Where(gocassa.Eq("session_id",0)).ReadOne(&result); err != nil {
        panic(err);
    }
```

I get:

```
panic: (*gocassa.singleOp) (0x905340,0xc820196160)

goroutine 1 [running]:
panic(0x905340, 0xc820196160)
    /opt/go/go/src/runtime/panic.go:481 +0x3e6
main.main()
    <somefile>.go:109 +0x854

```

cannot known why it sends out this error.

**Comment by crufter** [comment]
@slayercat it looks like you are missing a .Run() after your .ReadOne!

Try this:

```
if err:= sessionsTable.Where(gocassa.Eq("session_id",0)).ReadOne(&result).Run(); err != nil {
        panic(err);
 }
```
